apiVersion: v1
kind: Service
metadata:
  name: &service-name ${SERVICE_NAME_RENDERED:?}  # The name of the service.
  namespace: ${KUBERNETES_NAMESPACE:?}            # The namespace of the service.
  labels: &labels
    app: *service-name
spec:
  # Type of the service:
  #  - NodePort: creates public port on every machine
  #  - LoadBalancer: creates a load-balancer on tcp level automatically - we don't want that
  type: ClusterIP
  ports:                                # The ports that are to be exposed by the service.
    - port: 8080                        # External port towards the load balancer.
      targetPort: http                  # Internal port towards the deployment.
      protocol: TCP                     # Protocol for this port.
      name: http                        # Name of the port (free to choose).
    - port: 8081
      targetPort: status
      protocol: TCP
      name: status
  selector: *labels  # use all `labels` set in `Deployment.spec.template.metadata`